# H2 config
spring:
  datasource:
    url: jdbc:h2:mem:covid_19_vaccination
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
# API config
api:
  prefix: /api/v1
